### ISSUE TITLE
HTTP/1.1 405 Method Not Allowed Error on Mac

### ISSUE THREAD

**Issue by JohnTM** [XanDDemoX/DAVify-Codea#1]
I tried running it on my iPad Air 2 to my Macbook through Chrome/Safari/Firefox but website stays blank. Turning on SERVER_DEBUG reveals the following issue:

HTTP/1.1 405 Method Not Allowed
Allow: OPTIONS, PROPFIND
Cache-Control: no-cache
Connection: close
Date: Sun, 18 Jun 2017 03:54:19 GMT
Server: Codea-WebDAV-HTTP/1.1

**Comment by XanDDemoX** [comment]
Web browser access is unsupported. A WebDAV client is required.
